GET http://localhost:8072/accounts/holder/4
###
PUT http://localhost:8072/accounts/
Content-Type: application/json

{
    "accountNumber": 987678763,
    "accountType": "Savings",
    "accountBalance": 20994.4,
    "customer": 4
}
###
POST http://localhost:8072/accounts/
Content-Type: application/json

{
    "accountNumber":4565456545,
    "customer":2,
    "accountBalance":20994.4,
    "accountType":"Savings"
}
###
GET http://localhost:8072/accounts/